version: '3.8'

services:
  website-leganda:
    container_name: website-leganda
    # The official v2 Traefik docker image
    image: simachille/website-leganda:latest
    restart: always
    ports:
      # The HTTP port
      - "83:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website-leganda.rule=Headers(`X-Host`, `website-leganda`)"
      - "traefik.docker.network=applications-network"
      - "traefik.http.middlewares.serviceheaders.headers.accesscontrolalloworiginlist=*" 
      - "traefik.http.routers.service.middlewares=serviceheaders"

    networks:
      - applications-network
networks:
  applications-network:
    external: true
    name: applications-network