export const LOCAL_DNS = 'http://192.168.111.244:9090';//verifier ipconfig avant d'exécuter
export const PROD_DNS = "https://api.leganda.chillo.fr";
export const IMAGES_URL = `${PROD_DNS}/assets`;
export const BACKOFFICE_URL = `${PROD_DNS}/api/v1`;
export const ADS_ENDPOINT = "ad";
export const FAVORITE_ENDPOINT = "favorite";
export const ACCOUNT_ENDPOINT = "account";
export const ADDRESS_ENDPOINT = "address";
export const CATEGORY_ENDPOINT = "category";
export const GOOGLE_PACES_API_BASE_URL = 'https://maps.googleapis.com/maps/api/place';
export const GOOGLE_PACES_API_KEY = 'AIzaSyBoBBvzxlRlkbfYzZcHp8ALOwBk3YjfB-I';
export const MAP_ZOOM = 10;
export const GOOGLE_PACES_CENTER_COORDINATES = {lat: 48.117266,lng: -1.677793};
